catalogue_host : catalogue-{{ environment }}.sitaram.icu
user_host : user-{{ environment }}.sitaram.icu
cart_host : cart-{{environment}}.sitaram.icu
shipping_host : shipping-{{ environment }}.sitaram.icu
payment_host : payment-{{ environment }}.sitaram.icu