catalogue_host : catalogue-backend-alb{{ environment }}.sitaram.icu
user_host : user-backend-alb{{ environment }}.sitaram.icu
cart_host : cart-backend-alb{{ environment }}.sitaram.icu
shipping_host : shipping-backend-alb{{ environment }}.sitaram.icu
payment_host : payment-backend-alb{{ environment }}.sitaram.icu